### ISSUE TITLE
Problem in winload\__init__.py

### ISSUE THREAD

**Issue by Mambazx** [arseniypetrikor/lc-client#1]
When I execute \_\_init__.py in `winload ` I get the following error:

> Traceback (most recent call last):
>   File "C:\Users\Mambaz\\\_\_init__.py", line 70, in <module>
>     Winload().main()
>   File "C:\Users\Mambaz\\\_\_init__.py", line 61, in main
>     self.data['RAM'] = self.getData('MemoryChip get Capacity, FormFactor, Manufacturer, MemoryType')
>   File "C:\Users\Mambaz\\\_\_init__.py", line 33, in getData
>     return self.parseOutput(output)
>   File "C:\Users\Mambaz\\\_\_init__.py", line 25, in parseOutput
>     subresult[j] = i[data["headers"].index(j)]
> IndexError: list index out of range

**Comment by arseniypetrikor** [comment]
@Mambazx check now

**Comment by Mambazx** [comment]
I just cloned the repository and the error still the same.

P.S. I think Winload's bound method `clearList` is so "heavy" and so useless as bound method of the class. It can be the local function in `parseOutput` or simple lambda.

**Comment by Mambazx** [comment]
I have a suggestion for this issue:

```
    def parseOutput(self, text):
        result = []
        lines = [s for s in text.splitlines() if s.strip()]
        headers = [header.strip() for header in lines[0].split("  ") if header.strip()]

        for data_line in lines[1:]:
            for n, detail in enumerate([detail.strip() for detail in data_line.split("  ") if detail.strip()]):
                result.append({headers[n] : detail})

        return result
```

instead of your `parseOutput`
(Sorry for non-pep8 length of line)

**Comment by arseniypetrikor** [comment]
Checked it and it's worked. Will be added in next commit.
